/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Myth
 */
public class loadR extends javax.swing.JFrame {

    public int time_check = 0;

    /**
     * Creates new form tr
     */
    public loadR() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loading...");
        setAlwaysOnTop(true);
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        pBar.setForeground(new java.awt.Color(0, 51, 255));
        pBar.setStringPainted(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pBar, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pBar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        if(time_check==0){
        Thread t = new Thread() {

            @Override
            public void run() {
                AgendaView B = new AgendaView();
                try {
                    Random r = new Random();
                    int i = r.nextInt(4);
                    if (i == 0) {
                        pBar.setValue(10);
                        jLabel1.setText("Carregando servidores quanticos da NASA...");
                        this.sleep(3000);
                        pBar.setValue(30);
                        jLabel1.setText("Servidores entraram em greve...");
                        this.sleep(3000);
                        pBar.setValue(45);
                        jLabel1.setText("Carregando inteligencia artifical...");
                        this.sleep(3000);
                        jLabel1.setText("Falha ao carregar IA, ela se nega a ser carregada...");
                    }
                    pBar.setValue(60);
                    if (i == 1) {

                        pBar.setValue(10);
                        jLabel1.setText("Esfriando os processadores AMD...");
                        this.sleep(3000);
                        pBar.setValue(30);
                        jLabel1.setText("Aplicando nitrogenio liquido...");
                        this.sleep(3000);
                        pBar.setValue(45);
                        jLabel1.setText("Como se adiantasse...");
                        this.sleep(3000);
                        pBar.setValue(60);
                        jLabel1.setText("Comprando novos processadores...");
                    }
                    if (i == 2) {

                        jLabel1.setText("Coletando informações do usuario...");
                        pBar.setValue(10);
                        this.sleep(3000);
                        pBar.setValue(35);
                        jLabel1.setText("Hmm... melhor não mecher nisso...");
                        this.sleep(3000);
                        pBar.setValue(40);
                        jLabel1.setText("Ligando para a policia...");
                        this.sleep(3000);
                        pBar.setValue(60);
                        jLabel1.setText("A policia está de greve...");
                    }
                    if (i == 3) {

                        jLabel1.setText("Acionando motorres de fusão nuclear...");
                        pBar.setValue(10);
                        this.sleep(3000);
                        jLabel1.setText("Ligando motor secundario...");
                        pBar.setValue(30);
                        this.sleep(3000);
                        pBar.setValue(45);
                        jLabel1.setText("Procurando por erros dos estagiarios...");
                        this.sleep(3000);
                        pBar.setValue(60);
                        jLabel1.setText("Corrigindo erros dos estagiarios, pode levar um tempo...");
                    }
                    this.sleep(5000);
                    pBar.setValue(99);
                    jLabel1.setText("Programa Carregado... Saravá BSOD");
                    this.sleep(1000);
                    time_check = 1;
                    B.setVisible(true);

                } catch (InterruptedException ex) {
                    Logger.getLogger(loadR.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        };

        t.start();
        }

    }//GEN-LAST:event_formFocusGained

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost

        if (time_check == 1) {
            this.dispose();
        }
       
    }//GEN-LAST:event_formFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loadR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loadR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loadR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loadR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loadR().setVisible(true);
            }

        });

    }

    public final JFrame getMainFrame() {
        return this;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar pBar;
    // End of variables declaration//GEN-END:variables
}
